INSERT INTO controletotens.pergunta (CODIGO, CODENQUETE, PERGUNTA, TIPOPERGUNTA, ULTALT)
VALUES (1, 1, 'COMO ESTÁ O SANEAMENTO?', 'SINGLE', '2018-04-12T00:05:10');
INSERT INTO controletotens.pergunta (CODIGO, CODENQUETE, PERGUNTA, TIPOPERGUNTA, ULTALT)
VALUES (2, 1, 'GOSTA DO GOSTO DA ÁGUA?', 'SINGLE', '2018-04-12T00:10:15');
INSERT INTO controletotens.pergunta (CODIGO, CODENQUETE, PERGUNTA, TIPOPERGUNTA, ULTALT)
VALUES (3, 1, 'ESTÁ CHEGANDO COM FORÇA NA SUA CASA?', 'SINGLE', '2018-04-12T00:15:01');
INSERT INTO controletotens.pergunta (CODIGO, CODENQUETE, PERGUNTA, TIPOPERGUNTA, ULTALT)
VALUES (4, 1, 'MARQUE AS OPÇÕES QUE CONSIDERA SENDO ATENDIDAS COM PLENO SUPORTE ', 'MULTI', '2018-04-12T00:20:01');

INSERT INTO controletotens.pergunta (CODIGO, CODENQUETE, PERGUNTA, TIPOPERGUNTA)
VALUES (5, 4, 'É POSSÍVEL ENCONTRAR VAGAS NO CENTRO DA CIDADE? ', 'SINGLE');
INSERT INTO controletotens.pergunta (CODIGO, CODENQUETE, PERGUNTA, TIPOPERGUNTA)
VALUES (6, 4, 'QUANTO TEMPO LEVA PARA ACHAR ALGUMA VAGA', 'SINGLE');
INSERT INTO controletotens.pergunta (CODIGO, CODENQUETE, PERGUNTA, TIPOPERGUNTA)
VALUES (7, 4, 'QUAIS ALTERNATIVAS JULGA SEREM AS CORRETAS PARA RESOLVER O PROBLEMA DE ESTACIONAMENTO? ', 'SINGLE');


INSERT INTO controletotens.pergunta (CODIGO, CODENQUETE, PERGUNTA, TIPOPERGUNTA)
VALUES (8, 5, 'QUAIS PROBLEMAS COM A COLETA DE LIXO NO SEU BAIRRO?', 'MULTI');
INSERT INTO controletotens.pergunta (CODIGO, CODENQUETE, PERGUNTA, TIPOPERGUNTA)
VALUES (9, 5, 'NOTA PARA A COLETA DE LIXO', 'SINGLE');
INSERT INTO controletotens.pergunta (CODIGO, CODENQUETE, PERGUNTA, TIPOPERGUNTA)
VALUES (10, 5, 'DIA E HORÁRIO DE COLETA', 'SINGLE');

INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA, ULTALT)
VALUES (1, 1, 1, 'BOM', '2018-04-12T00:20:01');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA, ULTALT)
VALUES (2, 1, 1, 'RUIM', '2018-04-12T00:25:01');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA, ULTALT)
VALUES (3, 2, 1, 'SIM', '2018-04-12T00:26:01');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA, ULTALT)
VALUES (4, 2, 1, 'NÃO', '2018-04-12T00:26:30');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA, ULTALT)
VALUES (5, 3, 1, 'SIM', '2018-04-12T00:28:01');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA, ULTALT)
VALUES (6, 3, 1, 'NÃO', '2018-04-12T00:29:01');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA, ULTALT)
VALUES (7, 4, 1, 'ÁGUA LIMPA', '2018-04-12T00:30:01');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA, ULTALT)
VALUES (8, 4, 1, 'ENTREGA DA FATURA', '2018-04-12T00:31:01');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA, ULTALT)
VALUES (9, 4, 1, 'ESGOTO', '2018-04-12T00:31:01');

INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA)
VALUES (10, 5, 4, 'SIM');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA)
VALUES (11, 5, 4, 'NÃO');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA)
VALUES (12, 6, 4, 'SIM');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA)
VALUES (13, 6, 4, 'NÃO');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA)
VALUES (14, 7, 4, 'DIMINUIR O TEMPO DO PROJETO ESTAR NAS CARTELAS');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA)
VALUES (15, 7, 4, 'AUMENTAR GUARDAS DE TRÂNSITO');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA)
VALUES (16, 7, 4, 'CÂMERAS AUTOMATIZADAS PARA MULTAR AUTOMATICAMENTE QUEM ULTRAPASSAR O LIMITE DE TEMPO');

INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA)
VALUES (17, 8, 5, 'SUJEIRA DEIXADA');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA)
VALUES (18, 8, 5, 'FALTA DE COLETA DE LIXO');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA)
VALUES (19, 8, 5, 'COLETA EXPORÁDICA');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA)
VALUES (20, 8, 5, 'FALTA DE EDUCAÇÃO DOS COLABORES DA COLETA');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA)
VALUES (21, 9, 5, '1 - 5');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA)
VALUES (22, 9, 5, '6 - 8');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA)
VALUES (23, 9, 5, '9 - 10');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA)
VALUES (24, 10, 5, 'QUARTA E SEXTA AS 05:00');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA)
VALUES (25, 10, 5, 'SEGUNDA E TERÇA AS 10:00');
INSERT INTO controletotens.resposta (CODIGO, CODPERGUNTA, CODENQUETE, RESPOSTA)
VALUES (26, 10, 5, 'QUINTA E SÁBADO AS 16:00');